---
abstract: 'parse tiled game maps from http://www.mapeditor.org'
author:
  - 'Ran Eilam <eilara@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Games-TMX-Parser
requires:
  Compress::Zlib: '1.09'
  MIME::Base64: '3.15'
  Moo: '2.003004'
  Type::Tiny: '1.004004'
  XML::Twig: '3.39'
version: '0.91'
x_generated_by_perl: v5.26.2
x_serialization_backend: 'YAML::Tiny version 1.73'
